### PR TITLE
Make 'rc.path' absolute

### LINKED ISSUE #157: --path option writing to wrong destination
When I tried to set the `--path` option when installing a prebuild, it would append the `path` value twice.

For example:
`--path path/to/directory/`
`unpack resolved to .../path/to/directory/path/to/directory/`

I think this is because in `bin.js` a new process is spawned in the `path` directory when one is present:
https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/bin.js#L20

And then in `download.js` the `path` is appended onto the current directory, which it shouldn't because we are already in the directory of the `path`:
https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/download.js#L106

So I think in dowload we wouldn't want to check for `path` again, just always use `'.'`?

This just pertains to relative paths.

### PR DESCRIPTION
**Pull request by dunkmann00**
I went ahead and implemented the suggestion by @vweevers. This will make `rc.path` an absolute path.

This fixes #157.

### CODE REVIEW

**Comment by vweevers** [comment]
I would prefer to do it here:

https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/rc.js#L45-L47

So that we don't modify rc outside of rc. Along the lines of:

```js
rc.path = path.resolve(rc.path === true ? '.' : rc.path || '.')
```

**Comment by vweevers** [comment]
Can you update this test accordingly?

https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/test/rc-test.js#L33-L34

**Comment by dunkmann00** [comment]
I just saw that after I pushed it, I'll take a look!

What should I set as the correct path? Running the tests on Github vs locally will result in a different value for path.

**Comment by vweevers** [comment]
It's OK to use `path.resolve('../some/other/path')` in the test as well. Or more precisely (because the test uses a random temporary directory as the working directory): `path.resolve(tmp, '../some/other/path')`. One way to get that `tmp` variable is to pass it to the callback here:

https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/test/rc-test.js#L149

I.e. `cb(result, tmp)`

File: test/rc-test.js [hunk 1]
```diff
@@ -30,8 +30,8 @@ test('custom config and aliases', function (t) {
     t.equal(rc.version, rc.v, 'version alias')
     t.equal(rc.help, true, 'help is set')
     t.equal(rc.help, rc.h, 'help alias')
-    t.equal(rc.path, '../some/other/path', 'correct path')
-    t.equal(rc.path, rc.p, 'path alias')
+    t.equal(rc.path, path.resolve(tmp, '../some/other/path'), 'correct path')
+    t.equal(rc.path, path.resolve(tmp, rc.p), 'path alias')
```
Comment (vweevers) [inline test/rc-test.js:34]:
```suggestion
```

The second test has become meaningless, because `rc.p` now holds the original path (if any) while `rc.path` holds the absolute path. The test used to assert that `-p` is a command line alias for `--path`, which IMO we don't need to test because it's a behavior provided by the `rc` module. And because we don't reference `rc.p` anywhere else, it's also OK that `rc.p` no longer equals `rc.path`.

**Review by vweevers — APPROVED** [review]

**Comment by vweevers** [comment]
[6.1.4](https://github.com/prebuild/prebuild-install/releases/tag/v6.1.4). Thanks!
